name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Check formatting with Black
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          # Windows PowerShell command
          Get-ChildItem -Recurse -Include *.py | 
            Where-Object { $_.FullName -notmatch "\\env\\" -and $_.FullName -notmatch "\\.git\\" -and $_.FullName -notmatch "\\.github\\" } |
            ForEach-Object { python -m black --config pyproject.toml --check $_.FullName }
        else
          # Linux/Mac command
          python -m black --config pyproject.toml --check $(find . -name "*.py" -not -path "./env/*" -not -path "./.git/*" -not -path "./.github/*")
        fi
        
    - name: Run tests
      run: |
        pytest tests/
        
    - name: Lint with flake8
      run: |
        flake8 .
        
  # Uncomment and configure this when you're ready to deploy
  # deploy:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.11'
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install fastapi uvicorn
  #     - name: Deploy to Cloud Provider
  #       run: |
  #         # Add your deployment commands here
  #         echo "Deployment would happen here"