name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: List Python files
      run: |
        find . -name "*.py" -not -path "./venv/*" -not -path "./.git/*"
        
    - name: Check formatting with Black
      run: |
        for file in $(find . -name "*.py" -not -path "./venv/*" -not -path "./.git/*"); do
          black --check "$file"
        done
        
    - name: Run tests
      run: |
        pytest tests/
        
    - name: Lint with flake8
      run: |
        flake8 .
        
  # Uncomment and configure this when you're ready to deploy
  # deploy:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.11'
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install fastapi uvicorn
  #     - name: Deploy to Cloud Provider
  #       run: |
  #         # Add your deployment commands here
  #         echo "Deployment would happen here"