name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Check formatting with Black
      shell: pwsh
      run: |
        $pyFiles = Get-ChildItem -Recurse -Include *.py | 
            Where-Object { 
            $_.FullName -notmatch "\\env\\" -and 
            $_.FullName -notmatch "\\.git\\" -and 
            $_.FullName -notmatch "\\.github\\" 
            }
    
          foreach ($file in $pyFiles) {
          python -m black --config pyproject.toml --check $file.FullName
          }

    - name: Check formatting with Black
      shell: pwsh
      run: |
        ./check_formatting.ps1    

    - name: Run tests
      run: |
        pytest tests/
        
    - name: Lint with flake8
      run: |
        flake8 .
        
  # Uncomment and configure this when you're ready to deploy
  # deploy:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.11'
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install fastapi uvicorn
  #     - name: Deploy to Cloud Provider
  #       run: |
  #         # Add your deployment commands here
  #         echo "Deployment would happen here"