name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn pytest black flake8
        
    - name: Run tests
      run: |
        # Add your test command here when you have tests
        # For example: pytest
        echo "No tests yet"
        
    - name: Check formatting with Black
      run: |
        black --check .
        
    - name: Lint with flake8
      run: |
        flake8 .

    - name: Run tests
      run: |
        pytest tests/

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
  # Uncomment and configure this when you're ready to deploy
  # deploy:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.11'
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install fastapi uvicorn
  #     - name: Deploy to Cloud Provider
  #       run: |
  #         # Add your deployment commands here
  #         echo "Deployment would happen here"