name: Run Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi pytest httpx
    - name: Run tests
      run: |
        pytest -v C:\Users\muoro\OneDrive\Área de Trabalho\Facu\6º Semestre\DevOps\AS1\src\test_main.py